import { rest } from 'msw'

const publishedRecords = [
  {
    pharosID: 'id-for-row-1',
    rowNumber: 1,
    'Project name': 'row 1 - project name',
    Authors: 'row 1 - author',
    'Collection date': '2020-01-01',
    Latitude: 51.605671213229094,
    Longitude: -0.1836275557121708,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 1 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'negative',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': 'row 1 - spatial uncertainty',
  },
  {
    pharosID: 'id-for-row-2',
    rowNumber: 2,
    'Project name': 'row 2 - project name',
    Authors: 'row 2 - author',
    'Collection date': '2020-01-02',
    Latitude: 44.045060653285155,
    Longitude: -69.49469755894837,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 2 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-3',
    rowNumber: 3,
    'Project name': 'row 3 - project name',
    Authors: 'row 3 - author',
    'Collection date': '2020-01-03',
    Latitude: 28.463853,
    Longitude: 77.017051,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 3 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-4',
    rowNumber: 4,
    'Project name': 'row 4 - project name',
    Authors: 'row 4 - author',
    'Collection date': '2020-01-04',
    Latitude: 28.496934,
    Longitude: 77.22905,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 4 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-5',
    rowNumber: 5,
    'Project name': 'row 5 - project name',
    Authors: 'row 5 - author',
    'Collection date': '2020-01-05',
    Latitude: 28.694163,
    Longitude: 77.203785,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 5 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-6',
    rowNumber: 6,
    'Project name': 'row 6 - project name',
    Authors: 'row 6 - author',
    'Collection date': '2020-01-06',
    Latitude: 28.839478,
    Longitude: 77.296513,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 6 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-7',
    rowNumber: 7,
    'Project name': 'row 7 - project name',
    Authors: 'row 7 - author',
    'Collection date': '2020-01-07',
    Latitude: 28.59386,
    Longitude: 77.3293,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 7 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-8',
    rowNumber: 8,
    'Project name': 'row 8 - project name',
    Authors: 'row 8 - author',
    'Collection date': '2020-01-08',
    Latitude: 28.673795,
    Longitude: 77.175005,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 8 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-9',
    rowNumber: 9,
    'Project name': 'row 9 - project name',
    Authors: 'row 9 - author',
    'Collection date': '2020-01-09',
    Latitude: 28.645807,
    Longitude: 77.211287,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 9 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-10',
    rowNumber: 10,
    'Project name': 'row 10 - project name',
    Authors: 'row 10 - author',
    'Collection date': '2020-01-10',
    Latitude: 28.570047,
    Longitude: 77.186226,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'Bear',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-11',
    rowNumber: 11,
    'Project name': 'row 11 - project name',
    Authors: 'row 11 - author',
    'Collection date': '2020-01-11',
    Latitude: 28.510703,
    Longitude: 77.173869,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'Bear',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-12',
    rowNumber: 12,
    'Project name': 'row 12 - project name',
    Authors: 'row 12 - author',
    'Collection date': '2020-01-12',
    Latitude: 28.566669,
    Longitude: 77.333336,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'Bear',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-13',
    rowNumber: 13,
    'Project name': 'row 13 - project name',
    Authors: 'row 13 - author',
    'Collection date': '2020-01-13',
    Latitude: 28.35,
    Longitude: 77.13333,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'Bear',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-14',
    rowNumber: 14,
    'Project name': 'row 14 - project name',
    Authors: 'row 14 - author',
    'Collection date': '2020-01-14',
    Latitude: 28.615978,
    Longitude: 76.950722,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'Bear',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-15',
    rowNumber: 15,
    'Project name': 'row 15 - project name',
    Authors: 'row 15 - author',
    'Collection date': '2020-01-15',
    Latitude: 28.439358,
    Longitude: 77.3126,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'Bear',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-16',
    rowNumber: 16,
    'Project name': 'row 16 - project name',
    Authors: 'row 16 - author',
    'Collection date': '2020-01-16',
    Latitude: 28.415834,
    Longitude: 77.313755,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 16 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-17',
    rowNumber: 17,
    'Project name': 'row 17 - project name',
    Authors: 'row 17 - author',
    'Collection date': '2020-01-17',
    Latitude: 28.471731,
    Longitude: 77.331093,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 17 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-18',
    rowNumber: 18,
    'Project name': 'row 18 - project name',
    Authors: 'row 18 - author',
    'Collection date': '2020-01-18',
    Latitude: 28.478661,
    Longitude: 77.214305,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 18 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-19',
    rowNumber: 19,
    'Project name': 'row 19 - project name',
    Authors: 'row 19 - author',
    'Collection date': '2020-01-19',
    Latitude: 28.477662,
    Longitude: 77.239144,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 19 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-20',
    rowNumber: 20,
    'Project name': 'row 20 - project name',
    Authors: 'row 20 - author',
    'Collection date': '2020-01-20',
    Latitude: 28.44858,
    Longitude: 77.312477,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 20 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-21',
    rowNumber: 21,
    'Project name': 'row 21 - project name',
    Authors: 'row 21 - author',
    'Collection date': '2020-01-21',
    Latitude: 28.5543,
    Longitude: 77.18251,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 21 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-22',
    rowNumber: 22,
    'Project name': 'row 22 - project name',
    Authors: 'row 22 - author',
    'Collection date': '2020-01-22',
    Latitude: 28.529857,
    Longitude: 77.094785,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 22 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-23',
    rowNumber: 23,
    'Project name': 'row 23 - project name',
    Authors: 'row 23 - author',
    'Collection date': '2020-01-23',
    Latitude: 28.499278,
    Longitude: 77.252655,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 23 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-24',
    rowNumber: 24,
    'Project name': 'row 24 - project name',
    Authors: 'row 24 - author',
    'Collection date': '2020-01-24',
    Latitude: 28.682253,
    Longitude: 77.319908,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 24 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-25',
    rowNumber: 25,
    'Project name': 'row 25 - project name',
    Authors: 'row 25 - author',
    'Collection date': '2020-01-25',
    Latitude: 28.470352,
    Longitude: 77.285531,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 25 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-26',
    rowNumber: 26,
    'Project name': 'row 26 - project name',
    Authors: 'row 26 - author',
    'Collection date': '2020-01-26',
    Latitude: 28.589113,
    Longitude: 77.234456,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 26 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-27',
    rowNumber: 27,
    'Project name': 'row 27 - project name',
    Authors: 'row 27 - author',
    'Collection date': '2020-01-27',
    Latitude: 28.441595,
    Longitude: 77.200105,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 27 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-28',
    rowNumber: 28,
    'Project name': 'row 28 - project name',
    Authors: 'row 28 - author',
    'Collection date': '2020-01-28',
    Latitude: 28.521385,
    Longitude: 77.103423,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 28 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-29',
    rowNumber: 29,
    'Project name': 'row 29 - project name',
    Authors: 'row 29 - author',
    'Collection date': '2020-01-29',
    Latitude: 28.481983,
    Longitude: 77.245911,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 29 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-30',
    rowNumber: 30,
    'Project name': 'row 30 - project name',
    Authors: 'row 30 - author',
    'Collection date': '2020-01-30',
    Latitude: 28.614506,
    Longitude: 77.022857,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 30 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-31',
    rowNumber: 31,
    'Project name': 'row 31 - project name',
    Authors: 'row 31 - author',
    'Collection date': '2020-01-31',
    Latitude: 28.620566,
    Longitude: 77.312293,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 31 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-32',
    rowNumber: 32,
    'Project name': 'row 32 - project name',
    Authors: 'row 32 - author',
    'Collection date': '2020-02-01',
    Latitude: 28.544908,
    Longitude: 77.293518,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 32 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-33',
    rowNumber: 33,
    'Project name': 'row 33 - project name',
    Authors: 'row 33 - author',
    'Collection date': '2020-02-02',
    Latitude: 28.69197,
    Longitude: 77.26255,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 33 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-34',
    rowNumber: 34,
    'Project name': 'row 34 - project name',
    Authors: 'row 34 - author',
    'Collection date': '2020-02-03',
    Latitude: 28.422051,
    Longitude: 77.329834,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 34 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-35',
    rowNumber: 35,
    'Project name': 'row 35 - project name',
    Authors: 'row 35 - author',
    'Collection date': '2020-02-04',
    Latitude: 28.44581,
    Longitude: 77.19494,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 35 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-36',
    rowNumber: 36,
    'Project name': 'row 36 - project name',
    Authors: 'row 36 - author',
    'Collection date': '2020-02-05',
    Latitude: 28.580132,
    Longitude: 77.083597,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 36 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-37',
    rowNumber: 37,
    'Project name': 'row 37 - project name',
    Authors: 'row 37 - author',
    'Collection date': '2020-02-06',
    Latitude: 28.707297,
    Longitude: 77.152302,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 37 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-38',
    rowNumber: 38,
    'Project name': 'row 38 - project name',
    Authors: 'row 38 - author',
    'Collection date': '2020-02-07',
    Latitude: 28.493215,
    Longitude: 77.032135,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 38 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-39',
    rowNumber: 39,
    'Project name': 'row 39 - project name',
    Authors: 'row 39 - author',
    'Collection date': '2020-02-08',
    Latitude: 28.587982,
    Longitude: 77.166574,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 39 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-40',
    rowNumber: 40,
    'Project name': 'row 40 - project name',
    Authors: 'row 40 - author',
    'Collection date': '2020-02-09',
    Latitude: 28.695509,
    Longitude: 77.336441,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 40 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-41',
    rowNumber: 41,
    'Project name': 'row 41 - project name',
    Authors: 'row 41 - author',
    'Collection date': '2020-02-10',
    Latitude: 28.557907,
    Longitude: 77.214386,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 41 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-42',
    rowNumber: 42,
    'Project name': 'row 42 - project name',
    Authors: 'row 42 - author',
    'Collection date': '2020-02-11',
    Latitude: 28.413112,
    Longitude: 77.288969,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 42 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-43',
    rowNumber: 43,
    'Project name': 'row 43 - project name',
    Authors: 'row 43 - author',
    'Collection date': '2020-02-12',
    Latitude: 28.491899,
    Longitude: 77.236966,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 43 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-44',
    rowNumber: 44,
    'Project name': 'row 44 - project name',
    Authors: 'row 44 - author',
    'Collection date': '2020-02-13',
    Latitude: 28.547371,
    Longitude: 77.09819,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 44 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-45',
    rowNumber: 45,
    'Project name': 'row 45 - project name',
    Authors: 'row 45 - author',
    'Collection date': '2020-02-14',
    Latitude: 28.682368,
    Longitude: 77.031004,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 45 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-46',
    rowNumber: 46,
    'Project name': 'row 46 - project name',
    Authors: 'row 46 - author',
    'Collection date': '2020-02-15',
    Latitude: 28.398559,
    Longitude: 77.161436,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 46 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-47',
    rowNumber: 47,
    'Project name': 'row 47 - project name',
    Authors: 'row 47 - author',
    'Collection date': '2020-02-16',
    Latitude: 28.427187,
    Longitude: 77.206535,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 47 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-48',
    rowNumber: 48,
    'Project name': 'row 48 - project name',
    Authors: 'row 48 - author',
    'Collection date': '2020-02-17',
    Latitude: 28.546955,
    Longitude: 77.1468,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 48 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-49',
    rowNumber: 49,
    'Project name': 'row 49 - project name',
    Authors: 'row 49 - author',
    'Collection date': '2020-02-18',
    Latitude: 28.664242,
    Longitude: 77.120472,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 49 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-50',
    rowNumber: 50,
    'Project name': 'row 50 - project name',
    Authors: 'row 50 - author',
    'Collection date': '2020-02-19',
    Latitude: 28.496311,
    Longitude: 77.103516,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 50 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': 'row 50 - spatial uncertainty',
  },
  {
    pharosID: 'id-for-row-51',
    rowNumber: 51,
    'Project name': 'row 51 - project name',
    Authors: 'row 51 - author',
    'Collection date': '2020-02-20',
    Latitude: 51.605671213229094,
    Longitude: -0.1836275557121708,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 51 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'negative',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': 'Spatial uncertainty of the first record',
  },
  {
    pharosID: 'id-for-row-52',
    rowNumber: 52,
    'Project name': 'row 52 - project name',
    Authors: 'row 52 - author',
    'Collection date': '2020-02-21',
    Latitude: 44.045060653285155,
    Longitude: -69.49469755894837,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 52 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-53',
    rowNumber: 53,
    'Project name': 'row 53 - project name',
    Authors: 'row 53 - author',
    'Collection date': '2020-02-22',
    Latitude: 28.463853,
    Longitude: 77.017051,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 53 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-54',
    rowNumber: 54,
    'Project name': 'row 54 - project name',
    Authors: 'row 54 - author',
    'Collection date': '2020-02-23',
    Latitude: 28.496934,
    Longitude: 77.22905,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 54 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-55',
    rowNumber: 55,
    'Project name': 'row 55 - project name',
    Authors: 'row 55 - author',
    'Collection date': '2020-02-24',
    Latitude: 28.694163,
    Longitude: 77.203785,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 55 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-56',
    rowNumber: 56,
    'Project name': 'row 56 - project name',
    Authors: 'row 56 - author',
    'Collection date': '2020-02-25',
    Latitude: 28.839478,
    Longitude: 77.296513,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 56 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-57',
    rowNumber: 57,
    'Project name': 'row 57 - project name',
    Authors: 'row 57 - author',
    'Collection date': '2020-02-26',
    Latitude: 28.59386,
    Longitude: 77.3293,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 57 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-58',
    rowNumber: 58,
    'Project name': 'row 58 - project name',
    Authors: 'row 58 - author',
    'Collection date': '2020-02-27',
    Latitude: 28.673795,
    Longitude: 77.175005,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 58 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-59',
    rowNumber: 59,
    'Project name': 'row 59 - project name',
    Authors: 'row 59 - author',
    'Collection date': '2020-02-28',
    Latitude: 28.645807,
    Longitude: 77.211287,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 59 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-60',
    rowNumber: 60,
    'Project name': 'row 60 - project name',
    Authors: 'row 60 - author',
    'Collection date': '2020-02-29',
    Latitude: 28.570047,
    Longitude: 77.186226,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 60 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-61',
    rowNumber: 61,
    'Project name': 'row 61 - project name',
    Authors: 'row 61 - author',
    'Collection date': '2020-03-01',
    Latitude: 28.510703,
    Longitude: 77.173869,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 61 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-62',
    rowNumber: 62,
    'Project name': 'row 62 - project name',
    Authors: 'row 62 - author',
    'Collection date': '2020-03-02',
    Latitude: 28.566669,
    Longitude: 77.333336,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 62 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-63',
    rowNumber: 63,
    'Project name': 'row 63 - project name',
    Authors: 'row 63 - author',
    'Collection date': '2020-03-03',
    Latitude: 28.35,
    Longitude: 77.13333,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 63 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-64',
    rowNumber: 64,
    'Project name': 'row 64 - project name',
    Authors: 'row 64 - author',
    'Collection date': '2020-03-04',
    Latitude: 28.615978,
    Longitude: 76.950722,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 64 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-65',
    rowNumber: 65,
    'Project name': 'row 65 - project name',
    Authors: 'row 65 - author',
    'Collection date': '2020-03-05',
    Latitude: 28.439358,
    Longitude: 77.3126,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 65 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-66',
    rowNumber: 66,
    'Project name': 'row 66 - project name',
    Authors: 'row 66 - author',
    'Collection date': '2020-03-06',
    Latitude: 28.415834,
    Longitude: 77.313755,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 66 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-67',
    rowNumber: 67,
    'Project name': 'row 67 - project name',
    Authors: 'row 67 - author',
    'Collection date': '2020-03-07',
    Latitude: 28.471731,
    Longitude: 77.331093,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 67 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-68',
    rowNumber: 68,
    'Project name': 'row 68 - project name',
    Authors: 'row 68 - author',
    'Collection date': '2020-03-08',
    Latitude: 28.478661,
    Longitude: 77.214305,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 68 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-69',
    rowNumber: 69,
    'Project name': 'row 69 - project name',
    Authors: 'row 69 - author',
    'Collection date': '2020-03-09',
    Latitude: 28.477662,
    Longitude: 77.239144,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 69 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-70',
    rowNumber: 70,
    'Project name': 'row 70 - project name',
    Authors: 'row 70 - author',
    'Collection date': '2020-03-10',
    Latitude: 28.44858,
    Longitude: 77.312477,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 70 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-71',
    rowNumber: 71,
    'Project name': 'row 71 - project name',
    Authors: 'row 71 - author',
    'Collection date': '2020-03-11',
    Latitude: 28.5543,
    Longitude: 77.18251,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 71 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-72',
    rowNumber: 72,
    'Project name': 'row 72 - project name',
    Authors: 'row 72 - author',
    'Collection date': '2020-03-12',
    Latitude: 28.529857,
    Longitude: 77.094785,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 72 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-73',
    rowNumber: 73,
    'Project name': 'row 73 - project name',
    Authors: 'row 73 - author',
    'Collection date': '2020-03-13',
    Latitude: 28.499278,
    Longitude: 77.252655,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 73 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-74',
    rowNumber: 74,
    'Project name': 'row 74 - project name',
    Authors: 'row 74 - author',
    'Collection date': '2020-03-14',
    Latitude: 28.682253,
    Longitude: 77.319908,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 74 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-75',
    rowNumber: 75,
    'Project name': 'row 75 - project name',
    Authors: 'row 75 - author',
    'Collection date': '2020-03-15',
    Latitude: 28.470352,
    Longitude: 77.285531,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 75 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-76',
    rowNumber: 76,
    'Project name': 'row 76 - project name',
    Authors: 'row 76 - author',
    'Collection date': '2020-03-16',
    Latitude: 28.589113,
    Longitude: 77.234456,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 76 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-77',
    rowNumber: 77,
    'Project name': 'row 77 - project name',
    Authors: 'row 77 - author',
    'Collection date': '2020-03-17',
    Latitude: 28.441595,
    Longitude: 77.200105,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 77 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-78',
    rowNumber: 78,
    'Project name': 'row 78 - project name',
    Authors: 'row 78 - author',
    'Collection date': '2020-03-18',
    Latitude: 28.521385,
    Longitude: 77.103423,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 78 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-79',
    rowNumber: 79,
    'Project name': 'row 79 - project name',
    Authors: 'row 79 - author',
    'Collection date': '2020-03-19',
    Latitude: 28.481983,
    Longitude: 77.245911,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 79 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-80',
    rowNumber: 80,
    'Project name': 'row 80 - project name',
    Authors: 'row 80 - author',
    'Collection date': '2020-03-20',
    Latitude: 28.614506,
    Longitude: 77.022857,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 80 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-81',
    rowNumber: 81,
    'Project name': 'row 81 - project name',
    Authors: 'row 81 - author',
    'Collection date': '2020-03-21',
    Latitude: 28.620566,
    Longitude: 77.312293,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 81 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-82',
    rowNumber: 82,
    'Project name': 'row 82 - project name',
    Authors: 'row 82 - author',
    'Collection date': '2020-03-22',
    Latitude: 28.544908,
    Longitude: 77.293518,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 82 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-83',
    rowNumber: 83,
    'Project name': 'row 83 - project name',
    Authors: 'row 83 - author',
    'Collection date': '2020-03-23',
    Latitude: 28.69197,
    Longitude: 77.26255,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 83 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-84',
    rowNumber: 84,
    'Project name': 'row 84 - project name',
    Authors: 'row 84 - author',
    'Collection date': '2020-03-24',
    Latitude: 28.422051,
    Longitude: 77.329834,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 84 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-85',
    rowNumber: 85,
    'Project name': 'row 85 - project name',
    Authors: 'row 85 - author',
    'Collection date': '2020-03-25',
    Latitude: 28.44581,
    Longitude: 77.19494,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 85 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-86',
    rowNumber: 86,
    'Project name': 'row 86 - project name',
    Authors: 'row 86 - author',
    'Collection date': '2020-03-26',
    Latitude: 28.580132,
    Longitude: 77.083597,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 86 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-87',
    rowNumber: 87,
    'Project name': 'row 87 - project name',
    Authors: 'row 87 - author',
    'Collection date': '2020-03-27',
    Latitude: 28.707297,
    Longitude: 77.152302,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 87 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-88',
    rowNumber: 88,
    'Project name': 'row 88 - project name',
    Authors: 'row 88 - author',
    'Collection date': '2020-03-28',
    Latitude: 28.493215,
    Longitude: 77.032135,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 88 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-89',
    rowNumber: 89,
    'Project name': 'row 89 - project name',
    Authors: 'row 89 - author',
    'Collection date': '2020-03-29',
    Latitude: 28.587982,
    Longitude: 77.166574,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 89 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-90',
    rowNumber: 90,
    'Project name': 'row 90 - project name',
    Authors: 'row 90 - author',
    'Collection date': '2020-03-30',
    Latitude: 28.695509,
    Longitude: 77.336441,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 90 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-91',
    rowNumber: 91,
    'Project name': 'row 91 - project name',
    Authors: 'row 91 - author',
    'Collection date': '2020-03-31',
    Latitude: 28.557907,
    Longitude: 77.214386,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 91 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-92',
    rowNumber: 92,
    'Project name': 'row 92 - project name',
    Authors: 'row 92 - author',
    'Collection date': '2020-04-01',
    Latitude: 28.413112,
    Longitude: 77.288969,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 92 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-93',
    rowNumber: 93,
    'Project name': 'row 93 - project name',
    Authors: 'row 93 - author',
    'Collection date': '2020-04-02',
    Latitude: 28.491899,
    Longitude: 77.236966,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 93 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-94',
    rowNumber: 94,
    'Project name': 'row 94 - project name',
    Authors: 'row 94 - author',
    'Collection date': '2020-04-03',
    Latitude: 28.547371,
    Longitude: 77.09819,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 94 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-95',
    rowNumber: 95,
    'Project name': 'row 95 - project name',
    Authors: 'row 95 - author',
    'Collection date': '2020-04-04',
    Latitude: 28.682368,
    Longitude: 77.031004,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 95 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-96',
    rowNumber: 96,
    'Project name': 'row 96 - project name',
    Authors: 'row 96 - author',
    'Collection date': '2020-04-05',
    Latitude: 28.398559,
    Longitude: 77.161436,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 96 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-97',
    rowNumber: 97,
    'Project name': 'row 97 - project name',
    Authors: 'row 97 - author',
    'Collection date': '2020-04-06',
    Latitude: 28.427187,
    Longitude: 77.206535,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 97 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-98',
    rowNumber: 98,
    'Project name': 'row 98 - project name',
    Authors: 'row 98 - author',
    'Collection date': '2020-04-07',
    Latitude: 28.546955,
    Longitude: 77.1468,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 98 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-99',
    rowNumber: 99,
    'Project name': 'row 99 - project name',
    Authors: 'row 99 - author',
    'Collection date': '2020-04-08',
    Latitude: 28.664242,
    Longitude: 77.120472,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 99 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'id-for-row-100',
    rowNumber: 100,
    'Project name': 'row 100 - project name',
    Authors: 'row 100 - author',
    'Collection date': '2020-04-09',
    Latitude: 28.496311,
    Longitude: 77.103516,
    'Sample ID': null,
    'Animal ID': null,
    'Host species': 'row 100 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': 'row 100 - spatial uncertainty',
  },
]

const publishedRecordsMetadata = {
  possibleFilters: {
    project_name: {
      label: 'Project name',
      dataGridKey: 'Project name',
      options: ['Project A', 'Project B', 'Project C'],
    },
    researcher_name: {
      label: 'Author',
      dataGridKey: 'Author',
      options: ['Author A', 'Author B', 'Author C'],
    },
    host_species: {
      options: ['Species 1', 'Species 2', 'Species 3', 'Bear'],
      label: 'Host species',
      dataGridKey: 'Host species',
    },
    detection_target: {
      options: ['Target 1', 'Target 2', 'Target 3'],
      label: 'Detection target',
      dataGridKey: 'Detection target',
    },
    detection_outcome: {
      options: ['Negative', 'Positive'],
      label: 'Detection outcome',
      dataGridKey: 'Detection outcome',
    },
    pathogen: {
      options: ['Pathogen 1', 'Pathogen 2', 'Pathogen 3'],
      label: 'Pathogen',
      dataGridKey: 'Pathogen',
    },
    collection_start_date: {
      label: 'Collection date',
      type: 'date',
      earliestDateInDatabase: '1900-01-01',
      latestDateInDatabase: '2100-01-01',
    },
    collection_end_date: {
      label: 'Collection date',
      type: 'date',
      earliestDateInDatabase: '1900-01-01',
      latestDateInDatabase: '2100-01-01',
    },
  },
}

const handlers = [
  rest.get(
    `${process.env.GATSBY_API_URL}/published-records`,
    async (req, res, ctx) => {
      const params = req.url.searchParams
      const pageSize = Number(params.get('pageSize'))
      const page = Number(params.get('page'))
      const indexOfFirstRecordWanted = (page - 1) * pageSize

      // Handle some filters for testing purposes
      let recordsToReturn = [...publishedRecords]
      const collectionStartDate = params.get('collection_start_date')
      if (collectionStartDate) {
        recordsToReturn = recordsToReturn.filter(
          record => record['Collection date'] >= collectionStartDate
        )
      }
      const collectionEndDate = params.get('collection_end_date')
      if (collectionEndDate) {
        recordsToReturn = recordsToReturn.filter(
          record => record['Collection date'] >= collectionEndDate
        )
      }
      recordsToReturn = recordsToReturn.slice(
        indexOfFirstRecordWanted,
        indexOfFirstRecordWanted + pageSize
      )
      const data = { publishedRecords: recordsToReturn, isLastPage: false }
      return res(ctx.json(data))
    }
  ),
  rest.get(
    `${process.env.GATSBY_API_URL}/metadata-for-published-records`,
    async (_req, res, ctx) => {
      return res(ctx.json(publishedRecordsMetadata))
    }
  ),
]

export { handlers, publishedRecordsMetadata }
