import { rest } from 'msw'
import { PublishedRecordsResponse } from 'components/DataPage/TableView/utilities/fetchRecords'
import { Row } from 'components/PublicViews/PublishedRecordsDataGrid/PublishedRecordsDataGrid'

const publishedRecords = [
  {
    pharosID: 'project0-dataset0-row1',
    rowNumber: 1,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-01',
    Latitude: 51.605671213229094,
    Longitude: -0.1836275557121708,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 1 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'negative',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': 'row 1 - spatial uncertainty',
  },
  {
    pharosID: 'project0-dataset0-row2',
    rowNumber: 2,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-02',
    Latitude: 44.045060653285155,
    Longitude: -69.49469755894837,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 2 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row3',
    rowNumber: 3,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-03',
    Latitude: 28.463853,
    Longitude: 77.017051,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 3 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row4',
    rowNumber: 4,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-04',
    Latitude: 28.496934,
    Longitude: 77.22905,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 4 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row5',
    rowNumber: 5,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-05',
    Latitude: 28.694163,
    Longitude: 77.203785,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 5 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row6',
    rowNumber: 6,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-06',
    Latitude: 28.839478,
    Longitude: 77.296513,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 6 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row7',
    rowNumber: 7,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-07',
    Latitude: 28.59386,
    Longitude: 77.3293,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 7 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row8',
    rowNumber: 8,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-08',
    Latitude: 28.673795,
    Longitude: 77.175005,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 8 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row9',
    rowNumber: 9,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-09',
    Latitude: 28.645807,
    Longitude: 77.211287,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 9 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row10',
    rowNumber: 10,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-10',
    Latitude: 28.570047,
    Longitude: 77.186226,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'Bear',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row11',
    rowNumber: 11,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-11',
    Latitude: 28.510703,
    Longitude: 77.173869,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'Bear',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row12',
    rowNumber: 12,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-12',
    Latitude: 28.566669,
    Longitude: 77.333336,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'Bear',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row13',
    rowNumber: 13,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-13',
    Latitude: 28.35,
    Longitude: 77.13333,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'Bear',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row14',
    rowNumber: 14,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-14',
    Latitude: 28.615978,
    Longitude: 76.950722,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'Bear',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row15',
    rowNumber: 15,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-15',
    Latitude: 28.439358,
    Longitude: 77.3126,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'Bear',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row16',
    rowNumber: 16,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-16',
    Latitude: 28.415834,
    Longitude: 77.313755,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 16 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row17',
    rowNumber: 17,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-17',
    Latitude: 28.471731,
    Longitude: 77.331093,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 17 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row18',
    rowNumber: 18,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-18',
    Latitude: 28.478661,
    Longitude: 77.214305,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 18 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row19',
    rowNumber: 19,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-19',
    Latitude: 28.477662,
    Longitude: 77.239144,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 19 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row20',
    rowNumber: 20,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-20',
    Latitude: 28.44858,
    Longitude: 77.312477,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 20 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row21',
    rowNumber: 21,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-21',
    Latitude: 28.5543,
    Longitude: 77.18251,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 21 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row22',
    rowNumber: 22,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-22',
    Latitude: 28.529857,
    Longitude: 77.094785,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 22 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row23',
    rowNumber: 23,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-23',
    Latitude: 28.499278,
    Longitude: 77.252655,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 23 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row24',
    rowNumber: 24,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-24',
    Latitude: 28.682253,
    Longitude: 77.319908,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 24 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row25',
    rowNumber: 25,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-25',
    Latitude: 28.470352,
    Longitude: 77.285531,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 25 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row26',
    rowNumber: 26,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-26',
    Latitude: 28.589113,
    Longitude: 77.234456,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 26 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row27',
    rowNumber: 27,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-27',
    Latitude: 28.441595,
    Longitude: 77.200105,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 27 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row28',
    rowNumber: 28,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-28',
    Latitude: 28.521385,
    Longitude: 77.103423,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 28 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row29',
    rowNumber: 29,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-29',
    Latitude: 28.481983,
    Longitude: 77.245911,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 29 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row30',
    rowNumber: 30,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-30',
    Latitude: 28.614506,
    Longitude: 77.022857,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 30 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row31',
    rowNumber: 31,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-01-31',
    Latitude: 28.620566,
    Longitude: 77.312293,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 31 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row32',
    rowNumber: 32,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-01',
    Latitude: 28.544908,
    Longitude: 77.293518,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 32 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row33',
    rowNumber: 33,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-02',
    Latitude: 28.69197,
    Longitude: 77.26255,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 33 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row34',
    rowNumber: 34,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-03',
    Latitude: 28.422051,
    Longitude: 77.329834,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 34 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row35',
    rowNumber: 35,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-04',
    Latitude: 28.44581,
    Longitude: 77.19494,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 35 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row36',
    rowNumber: 36,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-05',
    Latitude: 28.580132,
    Longitude: 77.083597,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 36 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row37',
    rowNumber: 37,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-06',
    Latitude: 28.707297,
    Longitude: 77.152302,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 37 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row38',
    rowNumber: 38,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-07',
    Latitude: 28.493215,
    Longitude: 77.032135,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 38 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row39',
    rowNumber: 39,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-08',
    Latitude: 28.587982,
    Longitude: 77.166574,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 39 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row40',
    rowNumber: 40,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-09',
    Latitude: 28.695509,
    Longitude: 77.336441,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 40 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row41',
    rowNumber: 41,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-10',
    Latitude: 28.557907,
    Longitude: 77.214386,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 41 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row42',
    rowNumber: 42,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-11',
    Latitude: 28.413112,
    Longitude: 77.288969,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 42 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row43',
    rowNumber: 43,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-12',
    Latitude: 28.491899,
    Longitude: 77.236966,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 43 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row44',
    rowNumber: 44,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-13',
    Latitude: 28.547371,
    Longitude: 77.09819,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 44 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row45',
    rowNumber: 45,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-14',
    Latitude: 28.682368,
    Longitude: 77.031004,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 45 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row46',
    rowNumber: 46,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-15',
    Latitude: 28.398559,
    Longitude: 77.161436,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 46 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row47',
    rowNumber: 47,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-16',
    Latitude: 28.427187,
    Longitude: 77.206535,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 47 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row48',
    rowNumber: 48,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-17',
    Latitude: 28.546955,
    Longitude: 77.1468,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 48 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row49',
    rowNumber: 49,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-18',
    Latitude: 28.664242,
    Longitude: 77.120472,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 49 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row50',
    rowNumber: 50,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-19',
    Latitude: 28.496311,
    Longitude: 77.103516,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 50 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': 'row 50 - spatial uncertainty',
  },
  {
    pharosID: 'project0-dataset0-row51',
    rowNumber: 51,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-20',
    Latitude: 51.605671213229094,
    Longitude: -0.1836275557121708,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 51 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'negative',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': 'Spatial uncertainty of the first record',
  },
  {
    pharosID: 'project0-dataset0-row52',
    rowNumber: 52,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-21',
    Latitude: 44.045060653285155,
    Longitude: -69.49469755894837,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 52 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row53',
    rowNumber: 53,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-22',
    Latitude: 28.463853,
    Longitude: 77.017051,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 53 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row54',
    rowNumber: 54,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-23',
    Latitude: 28.496934,
    Longitude: 77.22905,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 54 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row55',
    rowNumber: 55,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-24',
    Latitude: 28.694163,
    Longitude: 77.203785,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 55 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row56',
    rowNumber: 56,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-25',
    Latitude: 28.839478,
    Longitude: 77.296513,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 56 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row57',
    rowNumber: 57,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-26',
    Latitude: 28.59386,
    Longitude: 77.3293,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 57 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row58',
    rowNumber: 58,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-27',
    Latitude: 28.673795,
    Longitude: 77.175005,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 58 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row59',
    rowNumber: 59,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-28',
    Latitude: 28.645807,
    Longitude: 77.211287,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 59 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row60',
    rowNumber: 60,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-02-29',
    Latitude: 28.570047,
    Longitude: 77.186226,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 60 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row61',
    rowNumber: 61,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-01',
    Latitude: 28.510703,
    Longitude: 77.173869,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 61 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row62',
    rowNumber: 62,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-02',
    Latitude: 28.566669,
    Longitude: 77.333336,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 62 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row63',
    rowNumber: 63,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-03',
    Latitude: 28.35,
    Longitude: 77.13333,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 63 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row64',
    rowNumber: 64,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-04',
    Latitude: 28.615978,
    Longitude: 76.950722,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 64 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row65',
    rowNumber: 65,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-05',
    Latitude: 28.439358,
    Longitude: 77.3126,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 65 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row66',
    rowNumber: 66,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-06',
    Latitude: 28.415834,
    Longitude: 77.313755,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 66 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row67',
    rowNumber: 67,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-07',
    Latitude: 28.471731,
    Longitude: 77.331093,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 67 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row68',
    rowNumber: 68,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-08',
    Latitude: 28.478661,
    Longitude: 77.214305,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 68 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row69',
    rowNumber: 69,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-09',
    Latitude: 28.477662,
    Longitude: 77.239144,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 69 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row70',
    rowNumber: 70,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-10',
    Latitude: 28.44858,
    Longitude: 77.312477,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 70 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row71',
    rowNumber: 71,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-11',
    Latitude: 28.5543,
    Longitude: 77.18251,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 71 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row72',
    rowNumber: 72,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-12',
    Latitude: 28.529857,
    Longitude: 77.094785,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 72 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row73',
    rowNumber: 73,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-13',
    Latitude: 28.499278,
    Longitude: 77.252655,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 73 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row74',
    rowNumber: 74,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-14',
    Latitude: 28.682253,
    Longitude: 77.319908,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 74 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row75',
    rowNumber: 75,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-15',
    Latitude: 28.470352,
    Longitude: 77.285531,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 75 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row76',
    rowNumber: 76,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-16',
    Latitude: 28.589113,
    Longitude: 77.234456,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 76 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row77',
    rowNumber: 77,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-17',
    Latitude: 28.441595,
    Longitude: 77.200105,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 77 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row78',
    rowNumber: 78,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-18',
    Latitude: 28.521385,
    Longitude: 77.103423,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 78 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row79',
    rowNumber: 79,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-19',
    Latitude: 28.481983,
    Longitude: 77.245911,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 79 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row80',
    rowNumber: 80,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-20',
    Latitude: 28.614506,
    Longitude: 77.022857,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 80 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row81',
    rowNumber: 81,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-21',
    Latitude: 28.620566,
    Longitude: 77.312293,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 81 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row82',
    rowNumber: 82,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-22',
    Latitude: 28.544908,
    Longitude: 77.293518,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 82 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row83',
    rowNumber: 83,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-23',
    Latitude: 28.69197,
    Longitude: 77.26255,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 83 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row84',
    rowNumber: 84,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-24',
    Latitude: 28.422051,
    Longitude: 77.329834,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 84 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row85',
    rowNumber: 85,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-25',
    Latitude: 28.44581,
    Longitude: 77.19494,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 85 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row86',
    rowNumber: 86,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-26',
    Latitude: 28.580132,
    Longitude: 77.083597,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 86 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row87',
    rowNumber: 87,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-27',
    Latitude: 28.707297,
    Longitude: 77.152302,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 87 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row88',
    rowNumber: 88,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-28',
    Latitude: 28.493215,
    Longitude: 77.032135,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 88 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row89',
    rowNumber: 89,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-29',
    Latitude: 28.587982,
    Longitude: 77.166574,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 89 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row90',
    rowNumber: 90,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-30',
    Latitude: 28.695509,
    Longitude: 77.336441,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 90 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row91',
    rowNumber: 91,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-03-31',
    Latitude: 28.557907,
    Longitude: 77.214386,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 91 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row92',
    rowNumber: 92,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-04-01',
    Latitude: 28.413112,
    Longitude: 77.288969,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 92 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row93',
    rowNumber: 93,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-04-02',
    Latitude: 28.491899,
    Longitude: 77.236966,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 93 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row94',
    rowNumber: 94,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-04-03',
    Latitude: 28.547371,
    Longitude: 77.09819,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 94 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row95',
    rowNumber: 95,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-04-04',
    Latitude: 28.682368,
    Longitude: 77.031004,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 95 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row96',
    rowNumber: 96,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-04-05',
    Latitude: 28.398559,
    Longitude: 77.161436,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 96 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row97',
    rowNumber: 97,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-04-06',
    Latitude: 28.427187,
    Longitude: 77.206535,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 97 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row98',
    rowNumber: 98,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-04-07',
    Latitude: 28.546955,
    Longitude: 77.1468,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 98 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row99',
    rowNumber: 99,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-04-08',
    Latitude: 28.664242,
    Longitude: 77.120472,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 99 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': '',
  },
  {
    pharosID: 'project0-dataset0-row100',
    rowNumber: 100,
    Researcher: [{ researcherID: 'res0', name: 'Researcher Zero' }],
    Project: 'Project Zero',
    'Collection date': '2020-04-09',
    Latitude: 28.496311,
    Longitude: 77.103516,
    'Sample ID': '',
    'Animal ID': '',
    'Host species': 'row 100 - host species',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': '',
    'Detection method': '',
    'Primer sequence': '',
    'Primer citation': '',
    'Detection target': '',
    'Detection target NCBI tax ID': '',
    'Detection outcome': 'positive',
    'Detection measurement': '',
    'Detection measurement units': '',
    Pathogen: '',
    'Pathogen NCBI tax ID': '',
    'GenBank accession': '',
    'Detection comments': '',
    'Organism sex': '',
    'Dead or alive': '',
    'Health notes': '',
    'Life stage': '',
    Age: '',
    Mass: '',
    Length: '',
    'Spatial uncertainty': 'row 100 - spatial uncertainty',
  },
]

export const publishedRecordsMetadata = {
  possibleFilters: {
    project_name: {
      label: 'Project',
      dataGridKey: 'Project',
      options: ['Project A', 'Project B', 'Project C'],
    },
    researcher_name: {
      label: 'Researcher',
      dataGridKey: 'Researcher',
      options: ['Researcher A', 'Researcher B', 'Researcher C'],
    },
    host_species: {
      options: ['Species 1', 'Species 2', 'Species 3', 'Bear'],
      label: 'Host species',
      dataGridKey: 'Host species',
    },
    detection_target: {
      options: ['Target 1', 'Target 2', 'Target 3'],
      label: 'Detection target',
      dataGridKey: 'Detection target',
    },
    detection_outcome: {
      options: ['Negative', 'Positive'],
      label: 'Detection outcome',
      dataGridKey: 'Detection outcome',
    },
    pathogen: {
      options: ['Pathogen 1', 'Pathogen 2', 'Pathogen 3'],
      label: 'Pathogen',
      dataGridKey: 'Pathogen',
    },
    collection_start_date: {
      label: 'Collection date',
      type: 'date',
      earliestDateInDatabase: '1900-01-01',
      latestDateInDatabase: '2100-01-01',
    },
    collection_end_date: {
      label: 'Collection date',
      type: 'date',
      earliestDateInDatabase: '1900-01-01',
      latestDateInDatabase: '2100-01-01',
    },
  },
}

type restGetCallback = Parameters<typeof rest.get>[1]
type Req = Parameters<restGetCallback>[0]
type Res = Parameters<restGetCallback>[1]
type Ctx = Parameters<restGetCallback>[2]

const getTypicalPublishedRecordsResponse = async (
  req: Req,
  _res: Res,
  _ctx: Ctx
) => {
  const params = req.url.searchParams
  const pageSize = Number(params.get('pageSize'))
  const page = Number(params.get('page'))
  const indexOfFirstRecordWanted = (page - 1) * pageSize

  // Handle some filters for testing purposes
  let recordsToReturn: Row[] = [...publishedRecords]
  const collectionStartDate = params.get('collection_start_date')
  if (collectionStartDate) {
    recordsToReturn = recordsToReturn.filter(
      record => record['Collection date'] >= collectionStartDate
    )
  }
  const collectionEndDate = params.get('collection_end_date')
  if (collectionEndDate) {
    recordsToReturn = recordsToReturn.filter(
      record => record['Collection date'] >= collectionEndDate
    )
  }
  recordsToReturn = recordsToReturn.slice(
    indexOfFirstRecordWanted,
    indexOfFirstRecordWanted + pageSize
  )
  const data: PublishedRecordsResponse = {
    publishedRecords: recordsToReturn,
    isLastPage: false,
  }
  return data
}

export const handlers = [
  rest.get(
    `${process.env.GATSBY_API_URL}/published-records`,
    async (req, res, ctx) => {
      const data = await getTypicalPublishedRecordsResponse(req, res, ctx)
      return res(ctx.json(data))
    }
  ),
  rest.get(
    `${process.env.GATSBY_API_URL}/metadata-for-published-records`,
    async (_req, res, ctx) => {
      return res(ctx.json(publishedRecordsMetadata))
    }
  ),
]

export const oneMillionRecordsHandler = rest.get(
  `${process.env.GATSBY_API_URL}/published-records`,
  async (req, res, ctx) => {
    const data = await getTypicalPublishedRecordsResponse(req, res, ctx)
    const params = req.url.searchParams
    data.recordCount = 1234567
    if (params.get('host_species')) data.matchingRecordCount = 567
    return res(ctx.json(data))
  }
)
