import { rest } from 'msw'

const publishedRecords = [
  {
    pharosID: 'UsEBEmUZbg2Pe-mQltet5OyiM6E-sgiGiaSiATD0S',
    rowNumber: 1,
    'Project name': 'Project for row 1',
    Authors: 'Alice Jones',
    'Collection date': '2020-01-01',
    Latitude: 51.605671213229094,
    Longitude: -0.1836275557121708,
    'Sample ID': '1',
    'Animal ID': '01',
    'Host species': 'Host species of the first record',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'negative',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': 'Spatial uncertainty of the first record',
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recOF87wF1s9R',
    rowNumber: 2,
    'Project name': 'Project for row 2',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 44.045060653285155,
    Longitude: -69.49469755894837,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Frog',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recBAFXj7cBxR',
    rowNumber: 3,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.463853,
    Longitude: 77.017051,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Newt',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recBNRc2lLuJM',
    rowNumber: 4,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.496934,
    Longitude: 77.22905,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-reccmkfVeYRG6',
    rowNumber: 5,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.694163,
    Longitude: 77.203785,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recu6OzOJeK8B',
    rowNumber: 6,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.839478,
    Longitude: 77.296513,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-rec9FwwuNM2Xn',
    rowNumber: 7,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.59386,
    Longitude: 77.3293,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recelK1p1fWqI',
    rowNumber: 8,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.673795,
    Longitude: 77.175005,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-rec7MI0QH97ID',
    rowNumber: 9,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.645807,
    Longitude: 77.211287,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recqrktfsRJ76',
    rowNumber: 10,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.570047,
    Longitude: 77.186226,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recjMvstympsC',
    rowNumber: 11,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.510703,
    Longitude: 77.173869,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recZrDqBo6CsV',
    rowNumber: 12,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.566669,
    Longitude: 77.333336,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-rec5DRLkdMAVG',
    rowNumber: 13,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.35,
    Longitude: 77.13333,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recgWnOzp8eSo',
    rowNumber: 14,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.615978,
    Longitude: 76.950722,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-rechWnGc1qKrk',
    rowNumber: 15,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.439358,
    Longitude: 77.3126,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-rec05swQCMoRz',
    rowNumber: 16,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.415834,
    Longitude: 77.313755,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recVRySAH3Fe9',
    rowNumber: 17,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.471731,
    Longitude: 77.331093,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recWPeWqy20Lt',
    rowNumber: 18,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.478661,
    Longitude: 77.214305,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recfGJC6Lab2G',
    rowNumber: 19,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.477662,
    Longitude: 77.239144,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recwfKKOoGZ5h',
    rowNumber: 20,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.44858,
    Longitude: 77.312477,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recneLVq9vVG6',
    rowNumber: 21,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.5543,
    Longitude: 77.18251,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recC18TvOTCIH',
    rowNumber: 22,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.529857,
    Longitude: 77.094785,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recpmkvNBTC9g',
    rowNumber: 23,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.499278,
    Longitude: 77.252655,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recGApGvRgK15',
    rowNumber: 24,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.682253,
    Longitude: 77.319908,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-rec8efOJ9P846',
    rowNumber: 25,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.470352,
    Longitude: 77.285531,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recCt1URkJyq5',
    rowNumber: 26,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.589113,
    Longitude: 77.234456,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recr5CQ8EeuEy',
    rowNumber: 27,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.441595,
    Longitude: 77.200105,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recWqO5y7EfZu',
    rowNumber: 28,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.521385,
    Longitude: 77.103423,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recRbFU8hLkT1',
    rowNumber: 29,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.481983,
    Longitude: 77.245911,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recWarng8Uxim',
    rowNumber: 30,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.614506,
    Longitude: 77.022857,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recNb9A32lA5V',
    rowNumber: 31,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.620566,
    Longitude: 77.312293,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recBRSPgGIF0I',
    rowNumber: 32,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.544908,
    Longitude: 77.293518,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-rec4WKsaBfJKk',
    rowNumber: 33,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.69197,
    Longitude: 77.26255,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-rec4XelSCvFdH',
    rowNumber: 34,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.422051,
    Longitude: 77.329834,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recnGJsbj1pHe',
    rowNumber: 35,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.44581,
    Longitude: 77.19494,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recV6OMJM9lgh',
    rowNumber: 36,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.580132,
    Longitude: 77.083597,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recq4IRUaKcX1',
    rowNumber: 37,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.707297,
    Longitude: 77.152302,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recH3hPt14gUb',
    rowNumber: 38,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.493215,
    Longitude: 77.032135,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-rec2vKw8D3818',
    rowNumber: 39,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.587982,
    Longitude: 77.166574,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recEp65tWReNJ',
    rowNumber: 40,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.695509,
    Longitude: 77.336441,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-reciFf8kRkEik',
    rowNumber: 41,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.557907,
    Longitude: 77.214386,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recVebga7cWtS',
    rowNumber: 42,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.413112,
    Longitude: 77.288969,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-rec7bXO6lLKJh',
    rowNumber: 43,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.491899,
    Longitude: 77.236966,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-rec5RJGyAxXiN',
    rowNumber: 44,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.547371,
    Longitude: 77.09819,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recvvSukINxj9',
    rowNumber: 45,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.682368,
    Longitude: 77.031004,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recnAgZZZ53Ki',
    rowNumber: 46,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.398559,
    Longitude: 77.161436,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-reclDR9332var',
    rowNumber: 47,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.427187,
    Longitude: 77.206535,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-rectqAV5fxBuO',
    rowNumber: 48,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.546955,
    Longitude: 77.1468,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-reczt7lEPPrYL',
    rowNumber: 49,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.664242,
    Longitude: 77.120472,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Vulpes vulpes',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-recxLBZmPQUZn',
    rowNumber: 50,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.496311,
    Longitude: 77.103516,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Host species of the last record of the first page',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty':
      'Spatial uncertainty of the last record of the first page',
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-asdf',
    rowNumber: 51,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.496311,
    Longitude: 77.103516,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': 'Host species of the first record of the second page',
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty':
      'Spatial uncertainty of the first record of the second page',
  },
  {
    pharosID: 'prjhYdBAyzZkM-setyM6Jkhdwz3-asdf',
    rowNumber: 52,
    'Project name': 'A project',
    Authors: 'Alice Jones',
    'Collection date': '2021-01-01',
    Latitude: 28.496311,
    Longitude: 77.103516,
    'Sample ID': '2',
    'Animal ID': '12',
    'Host species': null,
    'Host species NCBI tax ID': 0,
    'Collection method or tissue': null,
    'Detection method': null,
    'Primer sequence': null,
    'Primer citation': null,
    'Detection target': null,
    'Detection target NCBI tax ID': null,
    'Detection outcome': 'positive',
    'Detection measurement': null,
    'Detection measurement units': null,
    Pathogen: null,
    'Pathogen NCBI tax ID': null,
    'GenBank accession': null,
    'Detection comments': null,
    'Organism sex': null,
    'Dead or alive': null,
    'Health notes': null,
    'Life stage': null,
    Age: null,
    Mass: null,
    Length: null,
    'Spatial uncertainty': null,
  },
]

const publishedRecordsMetadata = {
  fields: {
    project_name: {
      label: 'Project name',
      dataGridKey: 'Project name',
      options: ['Project A', 'Project B', 'Project C'],
    },
    researcher_name: {
      label: 'Author',
      dataGridKey: 'Authors',
      options: ['Author A', 'Author B', 'Author C'],
    },
    host_species: {
      options: ['Species 1', 'Species 2', 'Species 3'],
      label: 'Host species',
      dataGridKey: 'Host species',
    },
    detection_target: {
      options: ['Target 1', 'Target 2', 'Target 3'],
      label: 'Detection target',
      dataGridKey: 'Detection target',
    },
    detection_outcome: {
      options: ['Negative', 'Positive'],
      label: 'Detection outcome',
      dataGridKey: 'Detection outcome',
    },
    pathogen: {
      options: ['Pathogen 1', 'Pathogen 2', 'Pathogen 3'],
      label: 'Pathogen',
      dataGridKey: 'Pathogen',
    },
    collection_start_date: {
      label: 'Collected on or after date',
      dataGridKey: 'Collection date',
      type: 'date',
      filterGroup: 'collection_date',
    },
    collection_end_date: {
      label: 'Collected on or before date',
      dataGridKey: 'Collection date',
      type: 'date',
      filterGroup: 'collection_date',
    },
  },
}

const handlers = [
  rest.get(
    `${process.env.GATSBY_API_URL}/published-records`,
    async (req, res, ctx) => {
      const params = req.url.searchParams
      const pageSize = Number(params.get('pageSize'))
      const page = Number(params.get('page'))
      console.log('page', page)
      console.log('pageSize', pageSize)
      const indexOfFirstRecordWanted = (page - 1) * pageSize
      const subsetOfRecords = publishedRecords.slice(
        indexOfFirstRecordWanted,
        indexOfFirstRecordWanted + pageSize
      )
      const data = { publishedRecords: subsetOfRecords, isLastPage: true }
      return res(ctx.json(data))
    }
  ),
  rest.get(
    `${process.env.GATSBY_API_URL}/metadata-for-published-records`,
    async (_req, res, ctx) => {
      return res(ctx.json(publishedRecordsMetadata))
    }
  ),
]

// Define some alternative handlers for use in specific tests
const routeThatReturnsNoPublishedRecords = rest.get(
  `${process.env.GATSBY_API_URL}/published-records`,
  async (_req, res, ctx) => {
    const data = { publishedRecords: [], isLastPage: true }
    return res(ctx.json(data))
  }
)

export {
  handlers,
  publishedRecordsMetadata,
  routeThatReturnsNoPublishedRecords,
}
