version: 2.1

credentials: &credentials
  - Verena AWS Credentials

workflows:
  version: 2
  build:
    jobs:
      # dev site
      - deploy:
          bucket: 's3://dev-pharos-frontend-2'
          distribution: 'E29CT6PE5VEJB6'
          api: 'https://d39bgqa0hu0mjm.cloudfront.net/prod'
          mapping_api: 'https://d39bgqa0hu0mjm.cloudfront.net/prod'
          client_id: '44vulabntl1hdi45vtvq0c7iop'
          user_pool_id: 'us-east-2_RR3m5a1fl'
          context: *credentials
          filters:
            branches:
              only:
                - dev

      # review site
      - deploy:
          bucket: 's3://review-pharos-frontend-2'
          distribution: 'E3IAEIH8QM2RIN'
          api: 'https://d74znvbck5xnf.cloudfront.net/prod'
          mapping_api: 'https://d74znvbck5xnf.cloudfront.net/prod'
          client_id: '3hcqevqa577mhqba9uhnphssct'
          user_pool_id: 'us-east-2_4bCcuIfOQ'
          context: *credentials
          filters:
            branches:
              only:
                - review

      # staging site
      - deploy:
          bucket: 's3://staging-pharos-frontend-2'
          distribution: 'E6PVRC1XI187A'
          api: 'https://d3je8e8pedawce.cloudfront.net/prod'
          mapping_api: 'https://d3je8e8pedawce.cloudfront.net/prod'
          client_id: 'o06ampns5let4mifsi2pn52el'
          user_pool_id: 'us-east-2_h1Xj2r9BX'
          context: *credentials
          filters:
            branches:
              only:
                - staging

      # prod site
      - deploy:
          bucket: 's3://prod-pharos-frontend-2'
          distribution: 'E61Z0UI7AL8G1'
          api: 'https://d98u7zobstgff.cloudfront.net/prod'
          mapping_api: 'https://d98u7zobstgff.cloudfront.net/prod'
          client_id: '2kf7i84imfo743pcv79kpn67qh'
          user_pool_id: 'us-east-2_mwSBSPXdc'
          context: *credentials
          filters:
            branches:
              only:
                - prod

orbs:
  aws-cli: circleci/aws-cli@4

jobs:
  deploy:
    working_directory: ~/repo

    docker:
      - image: cimg/node:lts

    parameters:
      bucket:
        type: string
      distribution:
        type: string
      api:
        type: string
      mapping_api:
        type: string
      client_id:
        type: string
      user_pool_id:
        type: string

    steps:
      - checkout
      - aws-cli/install

      - restore_cache:
          keys:
            - yarn-deps-{{ checksum "yarn.lock" }}
            - yarn-deps-

      - run:
          name: Add github.com to known hosts
          command: |
            mkdir ~/.ssh/
            echo $KNOWN_HOSTS >> ~/.ssh/known_hosts
            echo $KNOWN_HOSTS

      - run:
          name: Yarn Install
          command: yarn install --non-interactive

      - run:
          name: Typescript Checks
          command: yarn tsc

      - run:
          name: Run tests
          command: yarn run test

      - run:
          name: Gatsby build
          command: |
            yarn build \
            --api <<parameters.api>> \
            --mapping_api <<parameters.mapping_api>> \
            --user_pool_id <<parameters.user_pool_id>> \
            --client_id <<parameters.client_id>>

      - run:
          name: AWS S3 Sync to <<parameters.bucket>>
          command: aws s3 sync public/ <<parameters.bucket>> --delete

      - run:
          name: Run cloudfront invalidation
          command: |
            aws cloudfront create-invalidation \
            --distribution-id <<parameters.distribution>> \
            --paths "/*"

      - save_cache:
          key: yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - 'node_modules'
            - '.cache'
            - 'public'
